src/wp/Camera.cs

There's bug in Windows Phone 8.1 causing Seek on a DssPhotoStream not working properly.
https://connect.microsoft.com/VisualStudio/feedback/details/783252
But a mis-oriented file is better than nothing, so try and catch.

add try ... catch for getting image orientation

---

plugin.xml
src/windows/CameraProxy.js

- On Windows we should use filePicker instead of programmatically accessing user libs. This way the app doesnt have to depend on extra capabilities.
- Some refactoring to help on navigating code easier

CB-8706, CB-8707 saveToPhotoAlbum improvements and some refactoring

---

src/windows/CameraProxy.js

RandomAccessStream.copyAsync does not close destination stream, which is casuing a WinRT exception. Use copyAndCloseAsync instead.

CB-9413 Close RandomAccessStream once copied

---

README.md
jsdoc2md/TEMPLATE.md

Adds a much clearer warning about `allowEdit` on Android to the README. That particular feature has been the cause of many JIRA issues (see CB-7668)

CB-7668 Adding a sterner warning for allowedit on Android

---

README.md
jsdoc2md/TEMPLATE.md
src/android/CameraLauncher.java

When trying to get uncompressed images on Android using camera options like these:
``` javascript
{
destinationType : Camera.DestinationType.FILE_URL,
sourceType : Camera.PictureSourceType.CAMERA,
encodingType: Camera.EncodingType.PNG,
quality: 100,
saveToPhotoAlbum: true
}
```
the plugin will return a JPEG file with a .png filename. This pull request fixes the filename and documents the Android quirk that `encodingType` is ignored by the plugin on Android for uncompressed files. It currently does not make sense to actually provide PNG support in this case, because native camera apps return JPEG files and so converting to PNG does not improve quality, it just hurts performance. Same can be said for the gallery which just returns the selected file.

CB-9169 android: Fixed filetype for uncompressed images and added quirk

---

README.md
jsdoc2md/TEMPLATE.md
src/android/CameraLauncher.java

This fixes the long standing issue of the camera plugin crashing after receiving an Activity result when the Cordova Activity is killed in the background (CB-9189). Uses the new API for plugin save/restore that was merged into cordova-android recently.
*NOTE*: The link I put in the README is for Android docs that have been merged in to dev, but not published yet. It'll work once we do a docs release. Right now it's broken.

CB-9189 android: Implementing save/restore API to handle Activity destruction

---

src/browser/CameraProxy.js

The `MediaStream.stop()` method has been deprecated as of Chrome 47. We were using it, and it was generating an exception.
If `stop()` method is not found, instead stop each individual track (the new way of doing it).

CB-10502 Fix camera plugin exception in Chrome when click capture.

---

src/windows/CameraProxy.js

This is a workaround for a bug on Windows side till it gets resolved.

CB-10539: Commenting out the verySmallQvga maxResolution option

---

src/windows/CameraProxy.js

Fixing a minor syntax issue
@rakatyal @riknoll @nikhilkh Could you please review and merge this PR?

CB-10576: MobileSpec can't get results for Windows-Store 8.1 Builds

---

src/android/CameraLauncher.java

Default value is set to 80 on the java code, but doc says that default
value is 50.
I’m changing it just for making code clearer, but default value is set
to 50 to all platforms in Camera.js if no value is passed

Set android quality default value to 50 on the java code

---

appium-tests/android/android.spec.js
appium-tests/helpers/cameraHelper.js
appium-tests/ios/ios.spec.js

Android, iOS
https://issues.apache.org/jira/browse/CB-11296
* Adds a workaround for Appium bug when it clicks the wrong element.
* Tests fail fast if couldn't create a session
* Reuse old \<img\> element instead of creating a new one
Ran Appium tests on iOS real device (8.1) / simulator (8.4) and on Android (5.0 and 4.4) emulators

CB-11296: Appium: Better element clicking and session error handling

---

README.md
appium-tests/helpers/cameraHelper.js
appium-tests/ios/ios.spec.js
jsdoc2md/TEMPLATE.md
src/android/CameraLauncher.java
www/Camera.js
www/CameraConstants.js

Android, iOS
This PR resolves issues w/ the plugin (and tests), discovered by Appium tests:
1. on iOS plugin does not modify resultant file (no compression, format change or resizing is performed) when source is PHOTOGALLERY and output is NATIVE_URI. This is not well-documented in README and hadn't been taken into account when tests were being written.
2. On Android when output type is `PNG` and image has been picked from gallery, this results in skipping `jpeg` -> `png` conversion. The output file is saved in `jpeg` format even if file extension might be `.png`.
An example of failed tests can be found here: 
- For Android: [PLATFORM=android,PLUGIN=cordova-plugin-camera](http://cordova-ci.cloudapp.net:8080/view/Periodic%20builds/job/cordova-periodic-build/PLATFORM=android,PLUGIN=cordova-pl …

CB-11447 Fix Appium camera tests failures

---

appium-tests/helpers/cameraHelper.js
tests/tests.js

Any
Allows tests to use File plugin's resolveLocalFileSystemURL() method istead of deprecated resolveLocalFileSystemURI() method.
Tested Appium and Test Framework tests on Android 4.4 and iOS 8.4 emulators.

CB-11709 Tests should use resolveLocalFileSystemURL()

---

README.md
jsdoc2md/TEMPLATE.md

Windows (Windows Phone 8.1)
Updates plugin's docs to reflect WP8.1 quirk when calling `camera.getPicture` from location, different than app's start page
Not required

CB-11295 Add WP8.1 quirk when choosing image from photoalbum

---

appium-tests/android/android.spec.js

Android
- updated comments on how to run the tests.
- extra comments around functionality at certain points in the automation.
- stub of a resolution checker on test startup - still need to figure out acceptable values.
- moved session shutdown to an `afterAll` clause. 
- changed resolution determiner from using webview-based values to using the native windows dimensions. this helps as the webview values may be scaled down intentionally by manufacturers (via changing `window.devicePixelRatio`, for example). furthermore, since the screen dimensions are used purely for native UI automation using direct coordinates, better to use the dimensions reported by the native context rather than the web context.
- removed duplicate element calls.
Tested on local appium 1.6.3 environment on Android …

Android Appium test tweaks

---

appium-tests/ios/ios.spec.js

iOS
https://issues.apache.org/jira/browse/CB-12469
Updates the Appium tests to be able to run not only on iOS 9, but on iOS 10 too.
Tested on SauceLabs' iOS 9 and iOS 10 emulators. Did not test on local emulators!

CB-12469 (ios) Appium tests can now run on iOS 10

---

appium-tests/android/android.spec.js

Android
Enables Appium tests to handle native cling on Android which prevents them from removing temporary image from the image gallery.
https://issues.apache.org/jira/browse/CB-12618
Android 4.4: local and Sauce Labs run

CB-12618: (android) Appium tests: Handle native cling

---

appium-tests/android/android.spec.js
appium-tests/helpers/cameraHelper.js
appium-tests/ios/ios.spec.js

Android
https://issues.apache.org/jira/browse/CB-12764
Adapts Appium tests to run on Android 7 emulator on Sauce Labs
countless runs on Sauce Labs (i guess these tests currently don't work locally)

CB-12764: (android) Adapt Appium tests for Android 7

---

src/android/CameraLauncher.java
src/ios/CDVCamera.m

iOS, Android
changes cancel error message for iOS and Android to be consistent between these 2 platforms
opened Camera plugin on iOS and checked that error is correct in case when user cancel camera modal window

fix(error): changes error message for ios in case if user cancel

---

appium-tests/android/android.spec.js
appium-tests/ios/ios.spec.js

Android, iOS
https://issues.apache.org/jira/browse/CB-12982
Tries harder to create a session by increasing the timeout and introducing a retry mechanic.
A couple of runs with SauceLabs concurrency meter being 5/5.

CB-12982: (Android, iOS) Appium tests: try to create a session harder

---

appium-tests/ios/ios.spec.js

iOS
Reduces the run time of Appium tests on iOS 10
None

CB-12990 (iOS) Optimized Appium tests

---

appium-tests/android/android.spec.js
appium-tests/ios/ios.spec.js

Android, iOS
Fixes a problem in Appium tests which could lead to intermittent failures.
A couple of runs on Sauce Labs' Android 6.0 emulator.

CB-13002: (Android, iOS) Fix occasional Appium tests failures

---

README.md
package-lock.json
package.json
plugin.xml
src/osx/CDVCamera.h
src/osx/CDVCamera.m

HI all,
This pull request adds macOS support to cordova-plugin-camera.
I'm not sure if this project accepts new features, is open to community collaborations or even if I should be submitting this PR to git.apache.org... Some guidance will be truly appreciated 😄 
Here is a little demo of how it works:
The JS code looks like:
```
document.querySelector('#testCamera').addEventListener('click', function() {
navigator.camera.getPicture(onCameraOk, onError, {
sourceType: Camera.PictureSourceType.CAMERA,
destinationType: Camera.DestinationType.DATA_URL,
allowEdit: true,
encodingType: Camera.EncodingType.JPEG,
quality: 100,
targetWidth:  500,
targetHeight: 100,
})
})
document.querySelector('#testFile').addEventListener('click', function() {
navigator.camera.getPicture(onFileOk, onError, { …
```

CB-13421: (osx) Added macOS support

---

.travis.yml

Travis
Add build-tools-26.0.2 so travis doesn't complain about unaccepted licenses

CB-13747: Add build-tools-26.0.2 to travis

---

README.md
www/Camera.js

iOS
it modified on README.md.
it may be wrong.
In README.md
- `allowEdit` is `true` on default in CameraOptions.
but, actually `allowEdit` default value is `false`.
In a part of `www/Camera.js`
```
cameraExport.getPicture = function(successCallback, errorCallback, options) {
options = options || {};
var allowEdit = !!options.allowEdit;    // if do not set value, this allowEdit is false
};
```

change CameraOptions of README.md in ios

---

src/android/CameraLauncher.java

Android
Replacing Repeated String literals with final variables in CameraLauncher for having better maintainability and easier changes.
Making sure that everything builds fine, also, run my own tests for Android Camera and all pass fine.
I'm an old Apache Committer and a PMC member for another Apache project, so no worry about my CLA since I submitted it already.

CB-14047: (android) CameraLauncher: Replacing Repeated String literals with final variables

---

src/browser/CameraProxy.js

Browser
Updates CameraProxy.js to support video.srcObject and preserves backwards compatibility with URL.createObjectURL
Browser

CB-13384: (browser) Added deprecation of video.src compatibility

---

src/android/FileHelper.java

Handles both urls:
content://com.android.providers.downloads.documents/document/1111
content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Ffilename.pdf
Android
Fixes crash of certain URLs
manual testing
- [ x ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ x ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ? ] Added automated test coverage as appropriate for this change.

CB-14097: (android) Fix crash when selecting some files with getPicture

---

src/windows/CameraProxy.js

Windows 10
Adds extra content-type check when capturing photos without specifying targetWidth and/or targetHeight in options to preserve JPEG file extension.
ditto

CB-11714: (windows) added check for encoding in savePhoto() without height/width

---

types/index.d.ts

all
Fix TypeScript Definition for CameraPopoverOptions
Used in a TypeScript project and see that linter didn't complain after the change

CB-13837: fix TypeScript Definition for CameraPopoverOptions

---

README.md
src/ios/CDVCamera.m
tests/ios/CDVCameraTest/CDVCameraLibTests/CameraTest.m
tests/ios/package.json
tests/tests.js
types/index.d.ts
www/CameraPopoverOptions.js
www/ios/CameraPopoverHandle.js

IOS - Ipad only
Allow the user to set the popover Width and Height on Ipads
Modified the automated test cases to accommodate for the change.
Tested the plugin on the Ipad with different popover height and width as well as not specifying any.
- [x ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ x] Added automated test coverage as appropriate for this change.

CB-13865: (IOS-Ipad) Making popover Window Size configurable using popoverOptions - imagePicker

---

src/ios/CDVCamera.m

iOS
It removes iOS 8 checks as  cordova-ios only support iOS 9 and newer. (might still be breaking change as won't work on iOS 7?)
Removed the deprecated UIAlertView
Reworked the logic about requesting/checking permissions so it doesn't present the camera picker if the permission is not granted. As side effect of this, also fixes CB-14082, which had another [PR](https://github.com/apache/cordova-plugin-camera/pull/321) that won't be needed

CB-13813: (iOS) Remove old iOS code

---

src/android/CameraLauncher.java

Android
Properly return DATA_URL for ALLMEDIA when it has PNG or JPEG mime type
Closes #333
Fixes CB-12689 as side effect

Android: return DATA_URL for ALLMEDIA if it's an image

---

src/ios/CDVCamera.m

iOS
Fix this issue
#376  
Tested on a number of different iOS devices with different iOS versions (10, 11 12)
Automated tests

GH-376 (ios) fixes UIImagePickerController cancel handling for iOS11+

---

src/android/CameraLauncher.java

Android
Reads the exif data from the file on these cases:
-When destType = DATA_URL
-When file is selected from gallery.
-When targetHeight or targetWidth is set, quality is not 100 or correctOrientation is true
Tested on two differente android devices.
---
closes #329

GH-329: (android) Fixes issue: Exif data lost on many cases

---

src/android/CameraLauncher.java

Android
1. Organizing CameraLauncher imports.
2. Replacing Repeated String literals with final variables in CameraLauncher for having better maintainability and easier changes.
3. Fixing a mis-formatted comment.
Making sure that everything builds fine, also, run my own tests for Android Camera and all pass fine.
- [*] I've run the tests to see all new and existing tests pass
- [*] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [*] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [] I've updated the documentation if necessary

AAR-232: (android) Enhancement: Camera plugin code cleanup

---

.appveyor.yml
.travis.yml

All
`Node.js 4` is officially out of active LTS. However, it was still used `node.js 4` in the `Travis CI` and `AppVeyor`. This causes some builds to fail.
Update `Travis CI` and `AppVeyor` configuration files to use `node.js 6`. Also, update the `iOS` platform to use `xcode9` and `android` to use `build-tools-28.0.2`, because in the `paramedic` we already use newer versions.

Update CI Environment Setup for Node.js 6

---

src/android/CameraLauncher.java

Android
Fix NullPointerException error on some Android phones.
In some Android phones, `mimeType` is returned as `null`, this is why a NullPointerException is thrown. This defect is reported by issue #400 
Add a safe null checking before `equalsIgnoreCase`.

(Android) Fix NullPointerException error on some Android phones

---

src/ios/CDVCamera.m

iOS
It fixes #530, fixes #550, fixes #447, fixes #509, fixes #515
The plugin initializes a picker in the main thread now.
Previously made pull request by @ryaa: https://github.com/ryaa/cordova-plugin-camera/commit/a998ef45d902b514fc1dea53ebb24439034ac108
I've launched my app and tried to start camera session. It is ok now. No exceptions or low speed.

Fix UI API called on a background thread (#550, #530, #447)

---

src/ios/CDVCamera.m

ios
on iOS 13 the returned video url when picking from gallery becomes inaccessible, see #506
The PR makes a copy of the video and return the copy url
closes #506

fix(ios): return copy of video when picking from gallery on iOS 13

---

src/android/CameraLauncher.java

Android
We used to have to cache images on removable storage because devices did not have enough space, this is not an issue any longer, and it is better to let the system handle cache cleanup.
Remove conditional, and just default to application storage

[Android] Cache images in device storage, devices have enough space now.

---

src/ios/CDVCamera.m

ios
When using `<preference name="CameraUsesGeolocation" value="true" />`, the image is saved twice and calls tempFilePath, which could cause an infinite loop as reported on https://github.com/apache/cordova-plugin-camera/issues/591 (couldn't reproduce)
Instead of doing as on https://github.com/apache/cordova-plugin-camera/pull/592, which put the timestamp check inside the while to fix the possible infinite loop, this PR fixes the problem of the image being saved twice.
It removes the while because it was there for an older code that used an int that was incremented until the file didn't exist and used that int for the image name. Now that uses the timestamp and it's not called twice there is no need for the while.
fixes https://github.com/apache/cordova-plugin-camera/issues/591
closes …

fix(ios): tempFilePath called twice if using CameraUsesGeolocation

---

src/android/CameraLauncher.java

android
When picking files from the gallery, sometimes it can return "null" as the path, but on the success callback.
This PR will call the error callback if the file path is null (might be breaking if people is expecting null result for some reason?)
The PR also unify the logic, since at the moment this code returns a file url
```
navigator.camera.getPicture(onSuccess, onFail, { quality: 50,
destinationType: Camera.DestinationType.FILE_URI,
sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
targetWidth: 1024,
correctOrientation: true
});
```
but this code returns a content url
```
navigator.camera.getPicture(onSuccess, onFail, { quality: 50,
destinationType: Camera.DestinationType.FILE_URI,
sourceType: Camera.PictureSourceType.PHOTOLIBRARY
});
```
The PR will try to return a file url if …

fix(android): return error if file url is null

---

tests/plugin.xml
tests/tests.js

iOS
Remove the broken deprecated File Transfer Plugin from test & its test,

chore: remove deprecated file transfer plugin

---

README.md
package-lock.json
src/android/CameraLauncher.java
src/ios/CDVCamera.h
src/ios/CDVCamera.m
src/osx/CDVCamera.h
src/osx/CDVCamera.m
src/windows/CameraProxy.js
tests/tests.js
types/index.d.ts
www/CameraConstants.js

all
`NATIVE_URI` was only used on iOS and windows, on Android it acts like `FILE_URI`.
On iOS it returned `ALAssetsLibrary` urls that are not compatible with `WKWebView` and `ALAssetsLibrary` was deprecated on iOS 9, so I don't think it makes sense to keep this destination type since it's not supported by all platforms and it's deprecated on iOS.
also removes other usages of `ALAssetsLibrary` since it's deprecated
tested on real iOS device

breaking: remove NATIVE_URI DestinationType

---

RELEASENOTES.md

4.2.0 was never released, those changes should go in the 5.0.0 release section

chore: Update RELEASENOTES

---

plugin.xml

Android
Fixes https://github.com/apache/cordova-plugin-camera/issues/471
Fixes permission issue on Android.
Camera permission is generally only required if you're using the Camera APIs, which we don't however there are a few exceptions to this rule.
As of Android M, if you try to request the `CAMERA` permission without declaring it in the manifest, a security error is thrown. See the [Note](https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE) in the android documentation.
The camera plugin does request the `CAMERA` permission to handle an edge case where another plugin may include it in the manifest.
https://github.com/apache/cordova-plugin-camera/blob/5ae56cf8f07bcdfa090d928e7af3c8637521afce/src/android/CameraLauncher.java#L249-L251
Adds …

fix(android): Declare CAMERA permission

---

plugin.xml

Android
Reverts https://github.com/apache/cordova-plugin-camera/pull/670
The blame is actually not with the plugin, but rather the app. Camera plugin will request camera permissions if the camera permission is declared to support coexisting with other plugins that may need camera permission APIs, but otherwise the plugin does not require the camera permission to be declared and therefore it should not declare itself.
If the app uses a plugin that requires the camera permission, it is up to that plugin to add the camera permission itself.
This reverts commit 140e8861e30164da0861fec548d0aa2413197e12.
Ran `npm test`

Revert "fix(android): Declare CAMERA permission"

---

plugin.xml
src/android/CameraLauncher.java
src/android/GalleryPathVO.java

- Android
- Fixes #341
- Fixes #577
The saveToPhotoAlbum setting throws an exception while using the camera. (sourceType = CAMERA)
This results in a crash of the application. 
The first bug was reported in september 2018.
This PR only tries to solve the issue for the sourceType Camera.PictureSourceType.CAMERA, not for when the sourceType is PHOTOLIBRARY.
A reproduction of the issue can be done with https://github.com/PieterVanPoyer/cordova-camera-plugin-testing-app repo.
- saveToPhotoAlbum feature fixed by taken into count content - uri. (writeUncompressedImage method) ( see: apache#611 (comment) )
- make saveToPhotoAlbum future proof by using the MediaStore to insert the taken image
- made a method to calculate the compressFormat based on the encodingType (JPEG or PNG)
- layout of the …

Bugfix issue 341 save to photo gallery - Fixes #341, fixes #577

---

src/ios/CDVCamera.m

ios
on iOS 14 if using `<preference name="CameraUsesGeolocation" value="true" />` when trying to append the gps data to the exif the image gets corrupted
closes #674 
Used https://github.com/guilhermefarias/cordova-exif plugin to check the exif of the image after capturing on the provided sample app https://github.com/R4yYx/IOSSampleAPP

fix(ios): correctly append exif on iOS 14

---

src/android/GalleryPathVO.java

android
Add missing Apache license header to new JAVA file.
n/a

chore(android): add missing apache license header

---

src/android/CameraLauncher.java

Android
Fixes #665 
Fixes #696 
In the processResultFromCamera method, the imageFilePath is used.
https://github.com/apache/cordova-plugin-camera/blob/master/src/android/CameraLauncher.java#L475 
It was not restored when the activity was destroyed.
https://github.com/apache/cordova-plugin-camera/blob/b43c78b41997294d08fc8c17a3b286a5eba5fa6d/src/android/CameraLauncher.java#L1356
This resulted in a NullPointerException because the resulting sourcePath was null.
https://github.com/apache/cordova-plugin-camera/blob/b43c78b41997294d08fc8c17a3b286a5eba5fa6d/src/android/CameraLauncher.java#L473
So I've added the imageFilePath to the state Bundle in the saveInstance and the restoreInstance methods.
You can install and test the plugin (on Android) with next command.
````
npx cordova plugin remove …
```

Bugfix issue 665

---

package.json
plugin.xml

Android
Cordova-Android 10 uses AndroidX... Therefore we should lock this plugin version 5.x to Cordova-Android 9.x
Lock plugin 5.x to Cordova-Android 9.x
- n/a

chore: set the 5.x versions locked to cordova-android <10.0.0

---

package-lock.json

None
`package-lock` contained inconsistent version.
Corrected the version in `package-lock` to match with `package`
- n/a

fix: package-lock incorrect version

---

package-lock.json
package.json
plugin.xml
tests/package.json
tests/plugin.xml

None
Preparing for next major release that will be for Cordova-Android's next major.
Bump package and package-lock to 6.0.0-dev
- n/a

feat: bump plugin version for next major

---

plugin.xml

android
Fixes issues that were introduced with the new Android 11 (SDK 30) package visibility restrictions.
Explicitly sets the package visibility for:
* android.media.action.IMAGE_CAPTURE
* android.intent.action.GET_CONTENT
* android.intent.action.PICK
closes #673
Which is used by the camera and gallery.
* Tested on an Android 11 SDK 30 AVD

fix(android): supports sdk-30 package visibility

---

src/android/CameraLauncher.java
src/android/FileHelper.java

Android
Fixes #711 
When a .heic image is selected from a gallery it is converted to a .jpeg or .png image.
A .heic image is a format supported by Samsung phone's to take quality pictures.
But the .heic format cannot be handled by the webview part. (F.e. an image tag does not support it).
So the .heic image is converted by the Android build in HeicConverter.
In the webview part the returned image can be shown in an image tag or it can be send to the server.
Some extra code cleanup is done too.
Testing in the emulator with next repo: https://github.com/PieterVanPoyer/cordova-camera-plugin-testing-app/tree/features/issue-711-heif-format

Bugfix issue 711 heic format

---

plugin.xml
src/android/CameraLauncher.java
src/android/FileProvider.java

Android
Remove Support V4 and replace with AndroidX imports. This is for the Cordova-Android 10 release.
- n/a

feat(android)!: support AndroidX

---

.github/workflows/release-notify.yml

We want to test a new action that closes issues that are just asking for a new release and reduce noise. Let's start with this plugin.
This PR adds a new Github action built by me to add a comment and closes the issue if it looks like the issue is just created to ask for a release.

chore: add release notify action

---

src/android/FileHelper.java

Android
Select some videos or images return path error when Uri authority is FileProvider, then the app restarts.. That's why this bug is not always happening but it can be really annoying.
It's probably fixing the following issues (hard to say some descriptions are rather short): Resolves #573, resolves #531, resolves #548, resolves #554, resolves #558, resolves #563 
Checking if Uri authority is FileProvider for MediaStore content then find the URI.
Tested with most of my user's app and with my **Huawei p smart 2019 - Android 10** and with Samsung Galaxy S5.

fix(android): file path correction if Uri authority is FileProvider

---

src/android/CameraLauncher.java

Android
I use this plugin in multiple apps and sometimes users encounter errors when using the camera and ask for support.
To help with user support it would be useful to know the cause of the error by returning the exception message (where it exists) in the error message sent to the plugin error callback.
For example, this can be logged to analytics and used to help diagnose the cause of the error.
Where an exception is raised and the plugin invokes the error callback, append the exception message to the returned error message.
Tested on Android device by forcing an exception by appending "FOO" to the `imageUri`, i.e. change [line 615](https://github.com/apache/cordova-plugin-camera/blob/master/src/android/CameraLauncher.java#L615) to:
InputStream fileStream = …

fix(android): return exception message (where it exists) 

---

plugin.xml

Android
fixes https://github.com/apache/cordova-plugin-camera/issues/779
Change the queries element of plugin.xml so that not duplicate elements are created if other plugins or config.xml also contains a queries element
Add the following to the projects config.xml and add android platform. Only one queries element should be created in AppManifest.xml.
<config-file parent="queries" target="AndroidManifest.xml">
<package android:name="<name of package>" />
</config-file>
- [ x] I've run the tests to see all new and existing tests pass
- [x ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))

fix(android): update queries in plugin.xml

---

src/ios/CDVCamera.m

Incorporates the changes done by @ryaa that enable EXIF information to be retained on selected image.
https://github.com/apache/cordova-plugin-camera/commits/master/src/ios/CDVCamera.m
@ryaa: Enabled preserving exif data
Change to prevent saving the image file twice
Added authorization/permission request for camera roll
Added the fix to correctly handle iOS 14 new Photos picker permissions
@karlvr Fix background thread calling UI APIs

fix(ios): preserving EXIF data

---

README.md

closes https://github.com/apache/cordova-plugin-camera/issues/472
Documents ANDROIDX_CORE_VERSION variable and removes old install instructions since the plugin requires a greater version already and nobody should be using the old id at this point.

docs(README): Document ANDROIDX_CORE_VERSION variable

---

src/browser/CameraProxy.js

navigator.getUserMedia has been deprecated for a long time, most browsers still support it, but others like safari already removed it and others probably will in the future.
this PR uses navigator.mediaDevices.getUserMedia if available.

fix(browser): use navigator.mediaDevices.getUserMedia

---

src/android/CameraLauncher.java

Fix camera launcher https://github.com/apache/cordova-plugin-camera/issues/744
I invoked the camera plugin successfully

fix: set applicationId

---

package-lock.json
package.json
src/browser/CameraProxy.js
src/windows/CameraProxy.js
tests/tests.js
www/Camera.js
www/CameraPopoverHandle.js
www/CameraPopoverOptions.js
www/ios/CameraPopoverHandle.js

n/a
- Use latest eslint configurations
- Resolve audit warnings
- bump `@cordova/eslint-config@5.0.0`
- applied lint auto corrections
`npm t`

dep(dev)!: bump @cordova/eslint-config@5.0.0

---

package-lock.json
package.json
plugin.xml
src/android/CameraLauncher.java

android
Android 13 Support
- Rebase of #814
- Simplified the `getPermissions` method.
closes #814
resolves #825
- npm t
- built test app

feat(android)!: Android 13 support

---

plugin.xml

In https://github.com/apache/cordova-plugin-camera/pull/848 I didn't commit the plugin.xml changes with the platforms removals

chore: remove windows/osx from plugin.xml

---

plugin.xml
src/android/CameraLauncher.java

- Android
Google recommends using the Android photo picker in apps where it's not frequent to access these files instead of the READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions.
This should fix #866 
Removed the READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions and WRITE_EXTERNAL_STORAGE storage permission maxSdkVersion is set to 30.
Tested these changes on Android 10,11,12,13 and 14 devices.

fix(android): Removed read and write media permissions to allow to use Android photo picker #866

---

src/android/CameraLauncher.java
src/android/xml/camera_provider_paths.xml

Android
The file provider is what grants app delegates (such as the camera app) access for reading and/or writing. It is what allows the camera intent to write it's image to the app's internal cache directory. The previous configuration allowed access to the entire cache directory which could be perceived as a security risk.
Using a sub-directory will at least isolate access to that specific directory and won't expose other cache files that the app may have stored. The chosen directory is something that should only be used by this plugin, and the directory will be mostly empty assuming that users call the `cleanup` API. Worst case scenario it may have images that was previously captured by the user.
Update to provider to path to use a subdirectory, and updated the create code to use …

fix(android): Isolate provider access to a subdirectory

---

src/android/CameraLauncher.java

Android
Improper path construction is production a path such as `..../cacheIMG_xxx.jpg`.
To properly append a segment, it should use the `File` constructor second parameter, which appends a segment path to the base path.
Use the child segment parameter in `File` constructor.
Local testing and paramedic tests

fix(android): improper cache path construction during image manipulation

---

src/android/CameraLauncher.java

Android
The imageUri field is not properly restored if the activity is killed,
which can cause further issues.
This is because `imageFilePath` was used instead for the imageUri which only contains the
path of the original URI, losing the scheme in the process.
Serialize using `imageUri.toString()` instead of using the imageFilePath
paramedic testing + testing with `Don't Keep Activities` developer option enabled.

fix(android): Improper serialization of image uri in save instance state

---

src/android/CameraLauncher.java

Android
Makes data urls returned as actual URIs instead of just the base 64 encoded data.
This sisters PR https://github.com/apache/cordova-plugin-camera/pull/902
Closes https://github.com/apache/cordova-plugin-camera/issues/420
Prefixes the base64 with the data uri header.
paramedic tests passes
Manual testing

fix(android): Return data uris as an URI

---

src/android/CameraLauncher.java

This PR contains https://github.com/apache/cordova-plugin-camera/pull/901, will rebase after it's merged.
Android
closes https://github.com/apache/cordova-plugin-camera/issues/875
closes https://github.com/apache/cordova-plugin-camera/issues/783
closes https://github.com/apache/cordova-plugin-camera/issues/761
closes https://github.com/apache/cordova-plugin-camera/issues/422
closes https://github.com/apache/cordova-plugin-camera/issues/746
closes https://github.com/apache/cordova-plugin-camera/issues/347
The `finalLocation` returns raw file paths, which isn't always usable especially with Scoped Access Framework. Instead return the stringified URI, which has temporary permission granted.
With file plugin 8.1.1 `content://` paths are resolvable.
**NOTE**: I've since realised that …

fix(android): always return uris

---

src/browser/CameraProxy.js

Browser
Make the browser platform API consistent with v8 API changes of other platforms.
Removed data uri header stripping so that the returned string is the full DOM-usable Data uri string.
Unlike other platforms, browsers only supports DATA_URLs.
Manual testing

fix(browser): Make data uri be returned as actual URI strings

---

src/ios/CDVCamera.m

iOS
Android had a public API change so that it's returned data is URIs instead of paths.
This PR makes iOS do the same thing.
Unlike Android, iOS only ever deals with `file://` or `data:` URIs.
The most notable change `- (NSData*) processImage:(UIImage*) info:(NSDictionary*) options:(CDVPictureOptions*)` API implementation got moved to:
```obj-c
- (NSData*) processImage:(UIImage*) info:(NSDictionary*) options:(CDVPictureOptions*) outMime:(NSString**)
```
The old API signature calls on the new signature with a `nil` outMime, which if nil, the implementation will not set.
`outMime` is a new out parameter. If given an pointer-pointer to a NSString*, it will set it to the MIME type of the encoded type. It's used by a third new method:
```obj-c
- (NSString*) processImageAsDataUri:(UIImage*) …
```

fix(ios): Sync camera API return to match Android changes

---

src/android/CameraLauncher.java
src/android/ExifHelper.java

Android
Note this contains https://github.com/apache/cordova-plugin-camera/pull/902 will rebase after merge.
Raw system file paths are dangerous to use nowadays since they are often restricted, especially when dealing with external filesystems or filesystems that might not even be on-device (e.g. Google Drive).
Therefore all usages of `imageFilePath` was removed and replaced with `imageUri`.
Code that used `imageFilePath` generally now accepts a `Uri` instead or an `InputStream`.
Utility methods to read data into memory. getPageSize is an optimization to read a page of memory, which is usually 4kb but Android 15 devices may be shipped with 16kb page size devices.
There is a lot of disk usage when processing images which might be necessary back in the day when RAM is limited but modern …

refactor(android): replace image path usage with image uris

---

src/android/CameraLauncher.java

Will rebase after https://github.com/apache/cordova-plugin-camera/pull/906 & https://github.com/apache/cordova-plugin-camera/pull/902 is merged.
Android
fixes https://github.com/apache/cordova-plugin-camera/issues/891
closes https://github.com/apache/cordova-plugin-camera/issues/725
closes https://github.com/apache/cordova-plugin-camera/issues/660
This code existed since the beginning of time and it does not appear to be relevant anymore.
Duplicates does not occur, even with using DATA_URL or creating modifications via scaling.
Additionally querying the media store on API 28 and lower requires broad `READ_EXTERNAL_STORAGE` permission. If we can remove `numpics` and the usage of `queryImgDb` then we can make `READ/WRITE_EXTERNAL_STORAGE` optional.
With this change, on API 29+ no …

refactor(android): remove query img usage

---

README.md
src/android/CameraLauncher.java

Android
Depends on https://github.com/apache/cordova-plugin-camera/pull/907
closes https://github.com/apache/cordova-plugin-camera/issues/861
closes https://github.com/apache/cordova-plugin-camera/issues/876
Across all API levels that we support, no permissions are necessary for reading from
gallery. This is because we use the Media Store and gain temporary access to the content.
Across all API levels that we support, no permissions are necessary for capturing an image from the camera. This is because we use an internal app cache directory and we grant the camera app to use this path.
Where permissions might be necessary is with the `saveToPhotoAlbum` option. If enabled, non scoped access devices (API 24-28) do require `WRITE_EXTERNAL_STORAGE` to write to the device's gallery. API 29+ …

refactor(android): Make WRITE_EXTERNAL_STORAGE optional

---

plugin.xml

Android
This was intended to be part of https://github.com/apache/cordova-plugin-camera/pull/909
But I forgot to sync the change to `plugin.xml`
Removes the automatic declaration for `WRITE_EXTERNAL_STORAGE`, letting end users add it to their config.xml if they need it depending on their use cases.
YOLO paramedic (j.k. I've done lots of testing with and without the declaration)

fix(android): remove WRITE_EXTERNAL_PERMISSION

---

README.md
www/Camera.js

All
Deprecate allowEdit. It's already known and documented that on Android that it's unreliable and unsafe to use for reasons outside of our control. While it might be stable enough for iOS, I don't think we can ever provide the same capability for Android without grossly entering scope creep for the plugin responsibilities.
Generally speaking we should refrain from having platform-specific features. Therefore I propose to formally deprecate it in v8.0.0 so that we can indicate that we don't intend to support issues arising form using `allowEdit`, either on iOS or on android.
Note: While I have language indicating that it will be removed v9.0.0, that will obviously depend on who decides to make that release in the future, so don't consider have to consider it as a promise, but it should …

deprecation: allowEdit

---

README.md

n/a
Formatting cleanup of README for doc generation
- Removed trailing whitespace
n/a

chore: remove trailing whitespace from README

---

src/android/CameraLauncher.java

Android
fixes https://github.com/apache/cordova-plugin-camera/issues/925
Raise an error which is caught and propagated to the JS via the error callback as a string, matching the [documented](https://github.com/apache/cordova-plugin-camera?tab=readme-ov-file#cameraonerror--function) error signature.
Manual testing. Easiest to test by disabling the default camera application on a simulator.

fix(android): Error propagation when no Camera application is available
