- src/windows/CameraProxy.js
There's no css property such as z-order, use z-index instead.
> CB-8405 Use z-index instead of z-order

- src/windows/CameraProxy.js
Add missing take picture from file capability for WP8
> CB-8054 Support taking pictures from file for WP8

- src/windows/CameraProxy.js
Fixed 2 bugs in windows where we have trouble rotating the image on preview and saving
> CB-8404 Rotate camera feed with device orientation

- src/windows/CameraProxy.js
-fix PickAndContinue issue on WindowsPhone 10 
-fix emulator not correctly taking pictures WindowsPhone 8.1
-change default save location from Documents to Pictures
> CB-8943 fix PickAndContinue issue on Win10Phone

- src/windows/CameraProxy.js
aliased lots of the super long namespaces so we aren't fighting past with the 100 char line.
> [windows] major refactor : readability

- src/windows/CameraProxy.js
Improved the logic for camera/sensor rotation and adressed the camera issues.
> CB-8883 fix picture rotation issue

- src/windows/CameraProxy.js
Fix code changed after first pull request for this CB was created.
> Fix returning native url on windows.

- src/android/CameraLauncher.java
See bug description in [CB-9623](https://issues.apache.org/jira/browse/CB-9623)
> CB-9623 Fixes various issues when encodingType set to 'png'

- src/android/CameraLauncher.java
Fixes an issue where there were some permission requests missing when getting images from the PHOTOLIBRARY source. Any camera options that required outputting a modified image (width/height, allowEdit, correctOrientation, etc.) need the permission in order to preserve filenames and EXIF data in the final image.
> CB-9910 android: Add permission request for some gallery requests

- src/android/CameraLauncher.java
It was apparently decided a while back (CB-5749) that we should be saving the uncompressed image with `saveToPhotoAlbum` rather than the modified image when the camera options `quality`, `targetHeight`, `targetWidth`, etc. are given. iOS supports this behavior, but Android does not. This pull request changes the Android code so that when `saveToPhotoAlbum` is specified, the uncompressed image is saved to the album and the modified image is saved to the application's cache (and that URI is what is returned to the application). This also makes it so that DATA_URL actually saves images to the gallery when the flag is enabled (this was previously not the case). This might be a breaking change for some applications that relied on the old behavior (saving one image rather than two).
> CB-5479 android: changed saveToPhotoAlbum to save uncompressed images

- plugin.xml
- src/android/CameraLauncher.java
- src/android/PermissionHelper.java
As discussed on the mailing list
> CB-10319 android: Adding reflective helper methods for permission requests

- appium-tests/android/android.spec.js
- appium-tests/helpers/cameraHelper.js
- appium-tests/helpers/wdHelper.js
- appium-tests/ios/ios.spec.js
- tests/tests.js
https://issues.apache.org/jira/browse/CB-10397
> CB-10397 Added Appium tests

- appium-tests/android/android.spec.js
- appium-tests/helpers/wdHelper.js
https://issues.apache.org/jira/browse/CB-10619
> CB-10619 Appium tests: Properly switch to webview

- appium-tests/android/android.spec.js
- appium-tests/helpers/cameraHelper.js
- appium-tests/helpers/screenshotHelper.js
- appium-tests/helpers/wdHelper.js
- appium-tests/ios/ios.spec.js
Taking a screenshot on failure,
Retry taking a picture up to 3 times,
Try to restart the Appium session if it's lost
https://issues.apache.org/jira/browse/CB-10639
> CB-10639 Appium tests: Added some timeouts,

- .jshintrc
- .travis.yml
- README.md
- jsdoc2md/TEMPLATE.md
- package.json
- src/blackberry10/index.js
- src/browser/CameraProxy.js
- src/firefoxos/CameraProxy.js
- src/windows/CameraProxy.js
- tests/tests.js
- www/CameraPopoverHandle.js
[Jira issue](https://issues.apache.org/jira/browse/CB-10636)
> CB-10636 Add JSHint for plugins

- appium-tests/android/android.spec.js
- appium-tests/helpers/wdHelper.js
https://issues.apache.org/jira/browse/CB-10750
> CB-10750 Appium tests: fail fast if session is irrecoverable

- src/android/FileHelper.java
Now there is only a function to get the real path on API 11 and above.
> CB-10460 getRealPath return null in some cases

- .travis.yml
- tests/ios/CDVCameraTest/CDVCameraLibTests/CameraTest.m
- tests/ios/package.json
- tests/tests.js
Fixed tests project build failure.
Updated cordova-ios tests dependency version to latest published.
[Jira issue](https://issues.apache.org/jira/browse/CB-10865)
> CB-10865 Run ios native tests on Travis

- appium-tests/android/android.spec.js
https://issues.apache.org/jira/browse/CB-11162
> CB-11162 Appium tests: retry spec on failure

- .github/PULL_REQUEST_TEMPLATE.md
None!
Change the template that I am currently filling out so that the checklist message is in a comment
Absolutely none.
Please make sure these boxes are checked before submitting the PR. This checklist is intended as a quick reference, for complete details please see our [Contributor Guidelines](http://cordova.apache.org/contribute/contribute_guidelines.html). Thanks!
> Moving message in PR template to a comment

- plugin.xml
- src/android/CameraLauncher.java
- src/android/CordovaUri.java
- src/android/xml/provider_paths.xml
Android
This fixes the Camera Plugin for Android Nougat
Testing against master.
- [x ] [ICLA](http://www.apache.org/licenses/icla.txt) has been signed and submitted to secretary@apache.org.
- [ x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
> CB-11625: Fixes Camera issue w.r.t. content URIs by introducing android-commons dependency

- appium-tests/android/android.spec.js
Android
https://issues.apache.org/jira/browse/CB-12501
* Appium tests now use `elementByAndroidUIAutomator` selector instead of `elementByXPath`
* Appium tests don't save a screenshot on failure anymore (who needs screenshots when we have Sauce Labs videos?)
* Other minor improvements
Two tests runs on Sauce Labs: on Android 4.4 and on Android 5.1
> CB-12501 (Android) Appium tests don't use XPath selectors anymore

- README.md
Fixed incorrect "JIRA issue tracker" link in Readme
> Incorrect "JIRA issue tracker" link in Readme

- .travis.yml
iOS, Android
https://issues.apache.org/jira/browse/CB-12935
Enables paramedic builds on Travis
None, it will test itself
> CB-12935: (android, ios) Run paramedic tests on Travis

- .travis.yml
Android
https://issues.apache.org/jira/browse/CB-13000
Speed up testing on Travis CI by removing unnecessary installation steps.
A Travis CI run
> CB-13000: (CI) Speed up android builds

- package.json
> CB-13515 (all): Add 'protective' entry to cordovaDependencies

- src/ios/CDVCamera.m
iOS
Allow to properly present the camera in landscape
Tested on iPhone and iPod touch
> CB-13854(ios): fix Camera opens in portrait orientation on iphones

- README.md
- jsdoc2md/TEMPLATE.md
> Fix a mistake in the examples of usage descriptions

- plugin.xml
Android
Creates a variable so users can configure the com.android.support:support-v4 version
> CB-14017 (android): Make com.android.support:support-v4 version configurable

- package.json
- plugin.xml
- tests/plugin.xml
Bumping version again as I reverted the previous bumping on https://github.com/apache/cordova-plugin-camera/pull/363
> Bump minor version

- README.md
Removes deprecated platforms from README
Closes #380
> Remove deprecated platforms from docs

- README.md
Should have been removed on the windows phone 7 removal
> docs(README): remove orphan windows phone 7 note

- README.md
> docs(README): remove confusing comment

- package.json
- plugin.xml
- tests/package.json
- tests/plugin.xml
> breaking: bump version 5.0.0-dev

- .travis.yml
iOS Additional Tests are Failing
Goal is to make the tests pass.
> ci: fix additional tests

- .eslintrc.yml
- package.json
- src/browser/CameraProxy.js
- src/windows/CameraProxy.js
- tests/tests.js
- www/ios/CameraPopoverHandle.js
Use `@cordova/eslint-config@3.x`
> feat: migrate to @cordova/eslint-config@3.x

- package.json
Use Short Notation in `package.json`
> chore(package): use short notation

- .asf.yaml
Github
Update tags and only enable squash merge button like we do on other repos.
> chore(asf): Update GitHub repo metadata

- src/android/CameraLauncher.java
Android
Comments was left behind of a code change
Removed obsolete comments
Visual inspection of code.
> chore: Cleanup obsolete BuildConfig comments

- package-lock.json
- package.json
- plugin.xml
- tests/package.json
- tests/plugin.xml
Prepare for next major release
- bump plugin version to 7.0.0-dev.
- Updated cordovaDependencies (does not include requirements)
- npm t
> chore: bump plugin version 7.0.0-dev

- .github/workflows/chrome.yml
- .github/workflows/ios.yml
- .github/workflows/lint.yml
n/a
Sync CI configs with paramedic configs.
Updated GH Action Workflow
n/a
> ci(gh-action): sync with paramedic configs

- .github/workflows/android.yml
Sync android CI with paramamedic config.
> ci(android): Update Android CI to be compatible with cordova-android@13

- package-lock.json
- package.json
lint
was a minor version behind
update to 5.1.0.
All code continued to pass lint checks.
Ran lint
> chore: Update eslint config to 5.1.0
